# Generated by Django 4.1 on 2023-07-26 14:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название')),
                ('ocation', models.CharField(blank=True, choices=[('T', 'На чаепитие'), ('B', 'На день рождения'), ('W', 'На свадьбу')], max_length=30, verbose_name='Способ оплаты')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='картинка')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('levels_number', models.CharField(blank=True, choices=[('O', '1'), ('TW', '2'), ('TH', '3')], max_length=30, verbose_name='Способ оплаты')),
                ('form', models.CharField(blank=True, choices=[('RD', 'Круг'), ('S', 'Квадрат'), ('RL', 'Прямоугольник')], max_length=30, verbose_name='Способ оплаты')),
                ('topping', models.CharField(blank=True, choices=[('N', ''), ('W', ''), ('C', ''), ('M', ''), ('B', ''), ('CH', ''), ('S', '')], max_length=30, verbose_name='Способ оплаты')),
                ('berries', models.CharField(blank=True, choices=[('BK', ''), ('R', ''), ('BE', ''), ('S', '')], max_length=30, verbose_name='Способ оплаты')),
                ('decor', models.CharField(blank=True, choices=[('PS', ''), ('MR', ''), ('H', ''), ('PN', ''), ('MM', ''), ('MN', '')], max_length=30, verbose_name='Способ оплаты')),
                ('sign', models.CharField(blank=True, max_length=50, verbose_name='Надпись')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО клиента')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phonenumber', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('mail', models.CharField(blank=True, max_length=50, verbose_name='Электронная почта')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Заказ создан')),
                ('delivery_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время доставки')),
                ('comment', models.TextField(blank=True, max_length=400, verbose_name='Комментарий к заказу')),
                ('delivery_comment', models.TextField(blank=True, max_length=400, verbose_name='Комментарий курьеру')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cakeorder.cake', verbose_name='Название торта')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cakeorder.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
