# Generated by Django 4.2.3 on 2023-07-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
    ]
