# Generated by Django 4.1 on 2023-07-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='ocation',
        ),
        migrations.AddField(
            model_name='cake',
            name='occasion',
            field=models.CharField(blank=True, choices=[('T', 'На чаепитие'), ('B', 'На день рождения'), ('W', 'На свадьбу')], max_length=30, verbose_name='Повод'),
        ),
        migrations.AddField(
            model_name='cake',
            name='type',
            field=models.CharField(blank=True, choices=[('CG', 'Из каталога'), ('CM', 'Созданый пользователем')], max_length=30, verbose_name='Тип торта'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='berries',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ягоды'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decor',
            field=models.CharField(blank=True, max_length=30, verbose_name='Декор'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='form',
            field=models.CharField(blank=True, max_length=30, verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='levels_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Количество уровней'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='topping',
            field=models.CharField(blank=True, max_length=30, verbose_name='Топпинг'),
        ),
    ]
