# Generated by Django 4.2.3 on 2023-07-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeorder', '0002_alter_customer_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='type',
            field=models.CharField(blank=True, choices=[('CG', 'Из каталога'), ('CM', 'Созданый пользователем')], default='CM', max_length=30, verbose_name='Тип торта'),
        ),
    ]
