# Generated by Django 4.1 on 2023-07-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeorder', '0002_berries_price_decor_price_form_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='Ссылка на рекламу')),
                ('bitlink', models.CharField(blank=True, max_length=100, verbose_name='Сокращенная ссылка')),
                ('clicks', models.IntegerField(null=True, verbose_name='Количество переходов по ссылке')),
            ],
            options={
                'verbose_name': 'рекламная ссылка',
                'verbose_name_plural': 'рекламные ссылки',
            },
        ),
    ]
