# Generated by Django 4.2.3 on 2023-07-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeorder', '0003_alter_cake_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='cakeorder.form', verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='levels_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='cakeorder.levels_number', verbose_name='Количество уровней'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='sign',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Надпись'),
        ),
    ]
