# Generated by Django 4.2.3 on 2023-07-27 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeorder', '0004_berries_decor_form_levels_number_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='berries',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='decor',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='topping',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='berries',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='cakeorder.berries', verbose_name='Ягоды'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='cakeorder.decor', verbose_name='Декор'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='form',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='cakeorder.form', verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='levels_number',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='cakeorder.levels_number', verbose_name='Количество уровней'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='topping',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='cakeorder.topping', verbose_name='Топпинг'),
        ),
    ]
